import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Little-dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-green-950">
          <Navbar />
        </header>
        <main className="bg-green-100 h-full">{children}</main>
        <footer className="bg-green-950">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
