
export const metadata = {
  title: "Little-dev",
  description: "Generated by create next app",
  openGraph: {
    title: "Next.js",
    description: "The React Framework for the Web",
    url: "https://nextjs.org",
    siteName: "Next.js",
    images: [
      {
        url: "https://nextjs.org/og.png", 
        width: 800,
        height: 600,
      },
      {
        url: "https://nextjs.org/og-alt.png", 
        width: 1800,
        height: 1600,
        alt: "My custom alt",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};